### ISSUE TITLE
画面遷移図を作成する

### ISSUE THREAD

**Issue by YusukeYasui** [jphacks/F_2208#24]
## TODO

- [x] 必要な画面を考える
- [x] 画面同士の関連性を示す

### 関連課題
---

### 親課題

---

#### 備考

---

**Comment by yuuumiravy** [comment]
`- [ 必要な画面を考える]`は、`- [ ] 必要な画面を考える`とすると、TODOになります。
`- [スペース]スペースhogehoge`であることに注意
