### ISSUE TITLE
ダッシュボード画面を作成する

### ISSUE THREAD

**Issue by YusukeYasui** [jphacks/F_2208#30]
## What / Why
What:ダッシュボードの機能を持った画面が必要なため
Why:必要なので、、
## TODO

- [x] ダッシュボードに乗せる機能を洗い出す
  - [x] 必要あれば機能を渡した別画面を用意
- [x] レイアウトを考える
- [x] デザインを考える
- [x] 実装する
 - [x] コーディング
### 関連課題

---

### 親課題

---

#### 備考

---

**Comment by yuuumiravy** [comment]
`feature/#30_add_dashboard` は、 `feature/frontend/#30_add_dashboard`にすべきだね。次回からでいいので、把握お願いします〜
